import { test, expect, describe, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { loadIgnoreRules, shouldSkipDirectory, MAX_FILE_BYTES } from "../src/ignore.ts";
import { Watcher, walkWorkspace } from "../src/watcher.ts";
import { Workspace, nestedRepos } from "../src/workspace.ts";
import { openIndex } from "../src/db.ts";
import { Queue } from "../src/queue.ts";

let dir: string;

beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "crux-watch-"));
});
afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
});

describe("ignore rules", () => {
    test("build output and dependency trees are skipped", () => {
        const rules = loadIgnoreRules(dir);
        expect(rules.shouldSkip("node_modules/react/index.js")).toBe("denied-directory");
        expect(rules.shouldSkip("target/debug/build.rs")).toBe("denied-directory");
        expect(rules.shouldSkip("packages/app/dist/bundle.js")).toBe("denied-directory");
        expect(rules.shouldSkip(".git/objects/ab/cdef")).toBe("denied-directory");
    });

    test("the index itself is never indexed", () => {
        expect(loadIgnoreRules(dir).shouldSkip(".crux/index.db")).toBe("denied-directory");
    });

    test("editor scratch files are dropped — only the final rename matters", () => {
        const rules = loadIgnoreRules(dir);
        for (const temp of ["a.ts.tmp", "a.ts~", ".a.ts.swp", ".goutputstream-XYZ", "4913", "#a.ts#"]) {
            expect(rules.shouldSkip(temp)).toBe("temp-file");
        }
    });

    test("binaries and lockfiles are skipped by extension", () => {
        const rules = loadIgnoreRules(dir);
        expect(rules.shouldSkip("bun.lock")).toBe("denied-extension");
        expect(rules.shouldSkip("logo.png")).toBe("denied-extension");
        expect(rules.shouldSkip("app.min.js")).toBe("denied-extension");
    });

    test("real source is kept", () => {
        const rules = loadIgnoreRules(dir);
        expect(rules.shouldSkip("src/billing/retry.ts")).toBeNull();
        expect(rules.shouldSkip("main.go")).toBeNull();
    });

    test(".gitignore is honoured, including negations", async () => {
        await writeFile(join(dir, ".gitignore"), "*.log\n!keep.log\nsecret/\n");
        const rules = loadIgnoreRules(dir);

        expect(rules.shouldSkip("debug.log")).toBe("gitignored");
        expect(rules.shouldSkip("keep.log")).toBeNull();
        expect(rules.shouldSkip("secret/keys.ts")).toBe("gitignored");
        expect(rules.shouldSkip("src/app.ts")).toBeNull();
    });

    test(".cruxignore excludes things the user still wants in git", async () => {
        await writeFile(join(dir, ".cruxignore"), "fixtures/\n");
        const rules = loadIgnoreRules(dir);
        expect(rules.shouldSkip("fixtures/huge-schema.ts")).toBe("cruxignored");
    });

    test("content heuristics catch what a path cannot", () => {
        const rules = loadIgnoreRules(dir);

        expect(rules.shouldSkipContent("x", MAX_FILE_BYTES + 1)).toBe("too-large");
        expect(rules.shouldSkipContent("PK\0\0binary", 10)).toBe("binary");
        expect(rules.shouldSkipContent("// @generated by protoc\nexport const x = 1;", 40)).toBe("generated");
        expect(rules.shouldSkipContent(`const x=${"a".repeat(2000)};`, 2010)).toBe("minified");
        expect(rules.shouldSkipContent("export function fine() {}\n", 26)).toBeNull();
    });

    test("directories can be pruned without descending", () => {
        expect(shouldSkipDirectory("node_modules")).toBe(true);
        expect(shouldSkipDirectory("src")).toBe(false);
    });
});

describe("walking", () => {
    test("ignored subtrees are pruned rather than filtered afterwards", async () => {
        await mkdir(join(dir, "src"), { recursive: true });
        await mkdir(join(dir, "node_modules", "react"), { recursive: true });
        await writeFile(join(dir, "src", "app.ts"), "export const a = 1;");
        await writeFile(join(dir, "node_modules", "react", "index.js"), "module.exports = {};");
        await writeFile(join(dir, "bun.lock"), "{}");

        expect(await walkWorkspace(dir)).toEqual(["src/app.ts"]);
    });

    test("an empty workspace yields nothing rather than throwing", async () => {
        expect(await walkWorkspace(dir)).toEqual([]);
    });
});

/**
 * GitHub's macOS runners do not deliver fs.watch events at all — measured at
 * zero events after 20 s, while the identical test passes locally on macOS and
 * on Linux CI. It is an environment limitation of the runner, not of crux, so
 * these are skipped there rather than left red or deleted.
 *
 * The event-delivery path is still covered on every local macOS run and on
 * ubuntu-latest in CI. If this is ever fixed upstream, drop the guard.
 */
const watcherDeliveryWorks = !(process.env.CI && process.platform === "darwin");
const describeDelivery = watcherDeliveryWorks ? describe : describe.skip;

describeDelivery("the watcher", () => {
    /**
     * Wait for the queue to reach a depth, rather than sleeping a fixed amount.
     *
     * FSEvents and inotify deliver on their own schedule, and a loaded CI runner
     * is far slower than a laptop — a fixed sleep here failed on macOS CI while
     * passing locally. Poll for the condition, and only give up after a timeout
     * long enough that a failure means something is genuinely broken.
     */
    async function waitForDepth(queue: Queue, expected: number, timeoutMs = 20_000): Promise<number> {
        const deadline = Date.now() + timeoutMs;
        let depth = queue.depth().pending;
        while (Date.now() < deadline && depth < expected) {
            await Bun.sleep(25);
            depth = queue.depth().pending;
        }
        // Settle briefly so an over-emitting watcher shows up as an over-count
        // rather than passing because we stopped looking at the right moment.
        await Bun.sleep(150);
        return queue.depth().pending;
    }

    // Generous timeouts: these wait on the OS, not on our code. bun:test's
    // 5s default was the binding constraint on the macOS runner, not the
    // watcher.
    test("a save produces exactly one queue row despite several events", async () => {
        const db = openIndex(":memory:");
        const queue = new Queue(db);
        const watcher = new Watcher({ workspace: dir, queue, debounceMs: 50 });
        watcher.start();

        const target = join(dir, "retry.ts");
        // The editor pattern: temp file, rename over target, then modify.
        await writeFile(join(dir, ".goutputstream-XYZ"), "export const a = 1;");
        await Bun.$`mv ${join(dir, ".goutputstream-XYZ")} ${target}`.quiet();
        await writeFile(target, "export const a = 2;");

        const depth = await waitForDepth(queue, 1);
        watcher.stop();

        expect(depth).toBe(1);
        db.close();
    }, 30_000);

    test("ignored files never reach the queue", async () => {
        const db = openIndex(":memory:");
        const queue = new Queue(db);
        const watcher = new Watcher({ workspace: dir, queue, debounceMs: 50 });
        watcher.start();

        await mkdir(join(dir, "node_modules"), { recursive: true });
        await writeFile(join(dir, "node_modules", "dep.js"), "x");
        await writeFile(join(dir, "bun.lock"), "{}");

        // Nothing should ever arrive, so give the watcher real time to be wrong.
        await Bun.sleep(600);
        watcher.stop();

        expect(queue.depth().pending).toBe(0);
        db.close();
    });

    test("a burst of edits across files coalesces per path", async () => {
        const db = openIndex(":memory:");
        const queue = new Queue(db);
        const watcher = new Watcher({ workspace: dir, queue, debounceMs: 50 });
        watcher.start();

        for (let round = 0; round < 5; round++) {
            for (const name of ["a.ts", "b.ts", "c.ts"]) {
                await writeFile(join(dir, name), `export const x = ${round};`);
            }
        }

        const depth = await waitForDepth(queue, 3);
        watcher.stop();

        // Three distinct dirty files, not fifteen events.
        expect(depth).toBe(3);
        db.close();
    }, 30_000);

    test("status reports a degraded watcher rather than failing silently", () => {
        const db = openIndex(":memory:");
        const queue = new Queue(db);
        const reasons: string[] = [];
        const watcher = new Watcher({
            workspace: join(dir, "does-not-exist"),
            queue,
            onDegraded: (r) => reasons.push(r),
        });

        watcher.start();

        expect(watcher.status().watching).toBe(false);
        expect(reasons).toHaveLength(1);
        db.close();
    });
});

describe("the whole pipeline", () => {
    test("a file written on disk becomes searchable", async () => {
        await mkdir(join(dir, "src"), { recursive: true });
        await writeFile(
            join(dir, "src", "retry.ts"),
            "/** Retries a failed webhook. */\nexport class RetryPolicy {\n  execute() {}\n}\n",
        );

        const ws = new Workspace({ root: dir, memory: true });
        expect(await ws.coldIndex()).toBe(1);
        expect(await ws.drain()).toBe(1);

        const hits = ws.search("retry webhook");
        expect(hits[0]?.path).toBe("src/retry.ts");
        expect(ws.symbol("RetryPolicy")[0]?.kind).toBe("class");

        ws.close();
    });

    test("editing a file updates what queries return", async () => {
        await writeFile(join(dir, "a.ts"), "export function original() {}");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();
        expect(ws.symbol("original")).toHaveLength(1);

        await writeFile(join(dir, "a.ts"), "export function renamed() {}");
        ws.queue.enqueue({ workspace: dir, path: "a.ts", kind: "parse" });
        await ws.drain();

        expect(ws.symbol("original")).toHaveLength(0);
        expect(ws.symbol("renamed")).toHaveLength(1);

        ws.close();
    });

    test("deleting a file removes it from the index", async () => {
        await writeFile(join(dir, "a.ts"), "export function gone() {}");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();
        expect(ws.symbol("gone")).toHaveLength(1);

        await rm(join(dir, "a.ts"));
        ws.queue.enqueue({ workspace: dir, path: "a.ts", kind: "parse" });
        await ws.drain();

        // The file vanished: that is a delete, not an error.
        expect(ws.symbol("gone")).toHaveLength(0);
        ws.close();
    });

    test("re-running the cold index does no parsing work", async () => {
        await writeFile(join(dir, "a.ts"), "export const a = 1;");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();

        await ws.coldIndex();
        const outcomes: string[] = [];
        const worker = new (await import("../src/worker.ts")).ParseWorker({
            db: ws.db,
            workspace: dir,
            queue: ws.queue,
            onJob: (_j, o) => outcomes.push(o.status),
        });
        await worker.drain();

        expect(outcomes).toEqual(["skipped"]);
        ws.close();
    });

    test("a poison-pill file does not stop the rest of the workspace", async () => {
        await writeFile(join(dir, "good.ts"), "export const good = 1;");
        await writeFile(join(dir, "weird.ts"), "export function broken( {\n unclosed\n");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();

        // A syntax error is indexed anyway — never fail closed.
        expect(ws.symbol("good")).toHaveLength(1);
        expect(ws.status().queue.dead).toBe(0);
        ws.close();
    });

    test("files with no grammar are still searchable — Tier 0 needs no parser", async () => {
        await writeFile(
            join(dir, "ARCHITECTURE.md"),
            "# Architecture\n\nThe leader is elected with a heartbeat lease and a fencing check.\n",
        );
        await writeFile(join(dir, "a.ts"), "export const x = 1;");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();

        // Documentation is what people ask about most; leaving it unindexed
        // because Markdown has no tree-sitter grammar would be a large hole.
        expect(ws.search("heartbeat lease fencing")[0]?.path).toBe("ARCHITECTURE.md");
        ws.close();
    });

    test("coverage distinguishes lexical from syntactic", async () => {
        await writeFile(join(dir, "README.md"), "# Notes\n\nsome prose here\n");
        await writeFile(join(dir, "a.ts"), "export const x = 1;");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();

        const { coverage } = ws.status();
        // Both files are searchable, but only the .ts file has a syntax tree.
        expect(coverage.lexical).toBe(1);
        expect(coverage.syntactic).toBeLessThan(1);
        ws.close();
    });

    test("status reports what is indexed and what is missing", async () => {
        await writeFile(join(dir, "a.ts"), "export const a = 1;");

        const ws = new Workspace({ root: dir, memory: true });
        await ws.coldIndex();
        await ws.drain();

        const status = ws.status();
        expect(status.files).toBe(1);
        expect(status.symbols).toBeGreaterThan(0);
        expect(status.queue.pending).toBe(0);
        // Honest about what has not run yet.
        expect(status.coverage.precise).toBe(0);
        expect(status.coverage.vectors).toBe(0);

        ws.close();
    });
});

describe("workspace guards", () => {
    test("a folder of git repos is detected, so init can refuse it", async () => {
        for (const name of ["project-a", "project-b"]) {
            await mkdir(join(dir, name, ".git"), { recursive: true });
        }
        await mkdir(join(dir, "not-a-repo"), { recursive: true });

        expect((await nestedRepos(dir)).sort()).toEqual(["project-a", "project-b"]);
    });

    test("a directory that is itself a repo reports none", async () => {
        await mkdir(join(dir, ".git"), { recursive: true });
        await mkdir(join(dir, "vendored", ".git"), { recursive: true });

        // Submodules and vendored checkouts must not make a real repo look like
        // a folder of projects.
        expect(await nestedRepos(dir)).toEqual([]);
    });

    test("the walk stops at its limit rather than enumerating a huge tree", async () => {
        await mkdir(join(dir, "src"), { recursive: true });
        for (let i = 0; i < 50; i++) {
            await writeFile(join(dir, "src", `f${i}.ts`), "export const x = 1;");
        }

        expect(await walkWorkspace(dir, undefined, 10)).toHaveLength(10);
    });
});
