/**
 * Ignore rules — see 03-watcher.md.
 *
 * Applied in the watcher, BEFORE anything touches SQLite. Filtering after
 * enqueue means `npm install` writes 100,000 rows and then deletes them.
 *
 * Layers, cheapest first: a hard-coded denylist, then .gitignore, then
 * .cruxignore, then content heuristics that need the bytes.
 */

import ignoreFactory from "ignore";
import { join } from "node:path";

/** Directories that are never worth walking into. Checked by segment, not by pattern. */
const DENY_DIRS = new Set([
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    "out",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "vendor",
    "__pycache__",
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".gradle",
    ".idea",
    ".vscode",
    "coverage",
    ".turbo",
    ".cache",
    ".crux",
]);

/** Extensions that are never source, however they are named. */
const DENY_EXTENSIONS = new Set([
    ".lock",
    ".min.js",
    ".min.css",
    ".map",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".ico",
    ".svg",
    ".pdf",
    ".zip",
    ".gz",
    ".tar",
    ".bz2",
    ".xz",
    ".7z",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".o",
    ".a",
    ".class",
    ".jar",
    ".wasm",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".mp4",
    ".mp3",
    ".wav",
    ".mov",
    ".db",
    ".sqlite",
    ".bin",
]);

/**
 * Editor scratch files. A single save produces several of these and only the
 * final renamed path matters (03-watcher.md:80).
 */
const TEMP_PATTERNS = [
    /\.tmp$/,
    /~$/,
    /\.swp$/,
    /\.swx$/,
    /^\.#/,
    /^#.*#$/,
    /^4913$/,
    /\.goutputstream-/,
    /^\.~lock/,
    /\.crswap$/,
];

/** Files over this are skipped outright (09-operations.md). */
export const MAX_FILE_BYTES = 1024 * 1024;
/** Mean line length above this means minified. */
const MINIFIED_MEAN_LINE = 500;
/** Banners that mark a file as machine-written. */
const GENERATED_MARKERS = [/@generated/, /Code generated by/, /DO NOT EDIT/i, /auto-generated/i];

export type SkipReason =
    | "denied-directory"
    | "denied-extension"
    | "temp-file"
    | "gitignored"
    | "cruxignored"
    | "too-large"
    | "binary"
    | "minified"
    | "generated";

export interface IgnoreRules {
    /** Path-only check — no I/O, safe to call on every filesystem event. */
    shouldSkip(relativePath: string): SkipReason | null;
    /** Content check, for files that passed the path check. */
    shouldSkipContent(content: string, byteLength: number): SkipReason | null;
}

const basename = (p: string) => p.slice(p.lastIndexOf("/") + 1);

function readIgnoreFile(root: string, name: string): string[] {
    try {
        // Sync read at startup only: the watcher must never block on I/O.
        const text = require("node:fs").readFileSync(join(root, name), "utf8") as string;
        return text.split("\n");
    } catch {
        return [];
    }
}

export function loadIgnoreRules(root: string): IgnoreRules {
    // Hand-rolled gitignore matching is always subtly wrong — negations, nested
    // files, and directory semantics all have sharp edges. Use a real one.
    const gitignore = ignoreFactory().add(readIgnoreFile(root, ".gitignore"));
    const cruxignore = ignoreFactory().add(readIgnoreFile(root, ".cruxignore"));

    return {
        shouldSkip(relativePath: string): SkipReason | null {
            if (relativePath.length === 0) return "denied-directory";

            const segments = relativePath.split("/");
            for (const segment of segments.slice(0, -1)) {
                if (DENY_DIRS.has(segment)) return "denied-directory";
            }

            const name = basename(relativePath);
            if (DENY_DIRS.has(name)) return "denied-directory";
            for (const pattern of TEMP_PATTERNS) if (pattern.test(name)) return "temp-file";

            const lower = name.toLowerCase();
            for (const ext of DENY_EXTENSIONS) if (lower.endsWith(ext)) return "denied-extension";

            // `ignore` rejects absolute paths and paths escaping the root.
            if (!relativePath.startsWith("..")) {
                if (gitignore.ignores(relativePath)) return "gitignored";
                if (cruxignore.ignores(relativePath)) return "cruxignored";
            }
            return null;
        },

        shouldSkipContent(content: string, byteLength: number): SkipReason | null {
            if (byteLength > MAX_FILE_BYTES) return "too-large";

            // A NUL in the first 8 KB means binary. Cheaper and more reliable
            // than sniffing magic numbers for every format we might meet.
            if (content.slice(0, 8192).includes("\0")) return "binary";

            const head = content.slice(0, 4096);
            for (const marker of GENERATED_MARKERS) if (marker.test(head)) return "generated";

            const lines = content.split("\n");
            if (lines.length > 0 && content.length / lines.length > MINIFIED_MEAN_LINE) return "minified";

            return null;
        },
    };
}

/** Directory-level check, so a walk can prune whole subtrees without descending. */
export function shouldSkipDirectory(name: string): boolean {
    return DENY_DIRS.has(name);
}
